spring.application.name=login

spring.datasource.url=jdbc:mysql://localhost:3306/auth
spring.datasource.username=root
spring.datasource.password=harsh@2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2007.jainharsh@gmail.com
spring.mail.password=kmwz rcmr jkhs pxmj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080

spring.security.oauth2.client.registration.google.client-id=352611739724-t79an6clepoecc95asb02o7kd9sou7cg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=GOCe,email


spring.security.oauth2.client.registration.github.client-id=Ov23liSO5FKizRsW15wY
spring.security.oauth2.client.registration.github.client-secret=5f417fd1d2ff6be744eb7ed0bdSPX-ZJt8lsX20bvo_avgMDA_d8R0VW85
spring.security.oauth2.client.registration.google.scope=openid,profilb2335454ee191c
spring.security.oauth2.client.registration.github.scope=read:user,user:emails